<a href="https://colab.research.google.com/github/DP2196/ISLR/blob/master/numpy_icp4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as num

#generating random array of size 15 with integers in the range 1 to 20 (including)
arr = num.random.randint(1, high=21, size=15, dtype=int)
print (arr)

[18  9 20 18  1 18 17 20  1  1 15 15  9  6 15]


In [2]:
# reshape the created one dimensional array
reshape_arr= arr.reshape(3,5)
# printing the reshaped array
print(reshape_arr)

[[18  9 20 18  1]
 [18 17 20  1  1]
 [15 15  9  6 15]]


In [3]:
# printing the array shape
print(reshape_arr.shape)

(3, 5)


In [4]:
# finding max in each row
maxNum = num.amax(reshape_arr, axis=1)
# replace the max value in the row with zeros using num.where and num.isin functions
replaced_arr=num.where(num.isin(reshape_arr,maxNum), 0, reshape_arr)
# print replace array
print(replaced_arr)


[[18  9  0 18  1]
 [18 17  0  1  1]
 [ 0  0  9  6  0]]


In [5]:
# extracting the diagonal from the array
diag_arr=num.diag(replaced_arr)
print(diag_arr)

[18 17  9]


In [6]:
num.save('diagonal.npy', diag_arr) # saving the diagonal array to .npy format
diagonal_arr = num.load('diagonal.npy') # loading the .npy format file to a varaible and printing it
print(diagonal_arr)

[18 17  9]
